source "http://rubygems.org"

gem "rails", "~> 3.1.0"
gem "epic_fail", :path => '../../../epic_fail'
gem "jquery-rails"

group :development, :test do
  gem "sqlite3"
  gem "thin"
  gem "rspec-rails"
  gem "capybara"
  gem "factory_girl_rails"
  gem "guard-rspec"
  gem "rb-fsevent"
  gem "yard"
  gem "pry"
end