source "http://rubygems.org"

gem "rails", "~> 3.1.0"
gem "oil_change", :path => '../../../oil_change'

group :development, :test do
  gem "sqlite3"
  gem "thin"
  gem "rspec-rails"
  gem "capybara"
  gem "factory_girl_rails"
  gem "guard-rspec"
  gem "rb-fsevent"
  gem "yard"
  gem "pry"
end